import{a as s,S as c,i as u}from"./assets/vendor-DuKcLXOA.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function f(o){const n="https://pixabay.com",r="/api/",a=new URLSearchParams({key:"56397687-63b06f309fb1b7ea5ddc55358",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${n}${r}?${a}`;await s.get(e)}const m=document.querySelector("ul.gallery");function p(o){function n({name:e,LargeImageURL:t,previewURL:i}){return`<li>
            <a class="gallery-link" href="${t}">
              <img
              class="gallery-image"
              src="${i}" 
              alt="${e}"
            </a>
          </li>`}function r(e){return e.map(n).join("")}m.innerHTML=r(o),new c(".gallery a",{captionsData:"alt",captionDelay:250}).on("show.simplelightbox",function(){})}const l=document.querySelector("form.form"),d=document.querySelector('input[name="search-text"]');d.addEventListener("input",o=>{o.preventDefault()});l.addEventListener("submit",o=>{o.preventDefault();let r=new FormData(l).get("search-text");if(console.log(r),r.trim()==="")u.show({title:"hey",message:"fill in Empty field"});else{const a=f(r).catch(t=>{console.log(t)}),e=p(a);console.log(a),console.log(e)}});
//# sourceMappingURL=index.js.map
